### PR TITLE
Rename functions 

### PR DESCRIPTION
**Pull request by bircni**
## **Breaking Changes**

I renamed the functions to not have `set_` infant anymore to have the same styling as egui

### CODE REVIEW

**Comment by bircni** [comment]
@ItsEthra maybe this could be interesting for the new release including egui `0.29`

**Comment by ItsEthra** [comment]
Yes I'll try to update this to egui 0.29 and merge the pr tonight

**Comment by bircni** [comment]
Would be Great!

**Comment by bircni** [comment]
Will you release soon a new update to crates?

**Review by ItsEthra — APPROVED** [review]

**Pull request merged**
